### ISSUE TITLE
Have MetSim sample dataset correspond to the VIC and RVIC sample datasets

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/MetSim#100]
It would be nice if the MetSim, VIC, and RVIC sample datasets all covered the exact same domain and used the same domain file.  Then, a new user could test the output of MetSim by feeding it to VIC, and then to RVIC.

**Comment by arbennett** [comment]
The ascii and binary sample datasets provided are the Stehekin example from VIC, but I'm not sure what RVIC uses as a sample site.  I think we should keep the current netcdf example because it has 81 sites, whereas the Stehekin sample only has 16.  This makes it easier for people to play around with the parallel capabilities and get a feel for performance.

**Comment by tbohn** [comment]
The use of Stehekin for VIC was a rather arbitrary decision - made by me - a long time ago when I just needed to find some small basin to use as a sample dataset.  I'm by no means wed to it.  In fact, it would be better to use a basin that has a long time series of observed flows.  If a larger domain would be better for demonstrating MetSim, perhaps it would be better to find a basin that is both well-observed and of similar size to the MetSim example.

**Comment by tbohn** [comment]
A few potential candidates could be the Colorado R. above CAMEO, Feather R. above Oroville Dam, and Klamath R.
