### ISSUE TITLE
Speed up `calc_solar_geom()`

### ISSUE THREAD

**Issue by arbennett** [UW-Hydro/MetSim#3]
Currently the `calc_solar_geom()` function takes approximately 85% of the runtime of MTCLIM.  It seems like it should be easy to lower this runtime quite significantly due to two large loops.

**Comment by arbennett** [comment]
Improved in #10, but I would still like to leave this open because there's room for further improvement.  This portion of the calculation still take ~40% of the runtime of MetSim.

**Comment by jhamman** [comment]
Something to look at is @klapo's [solargeo](https://github.com/klapo/solargeo). It is a different (@klapo would say more accurate) way to calculate solar geometry. He optimized it a bit with Cython.

**Comment by bartnijssen** [comment]
Let's not worry too much about this for now. I'd rather have a working version that reproduces earlier results before we dive into this. At this point this falls under the heading "premature optimization" since the choice of solar geometry calculation does not affect the overall structure of the code.

**Comment by klapo** [comment]
Just for your reference, the current version of MTCLIM doesn't calculate orbital parameters correctly. It puts perihelion and aphelion at the wrong time of year. I suspect there is some compensating going on since MTCLIM performs well overall.

The orbital parameters also give you a bad sub-daily disaggregation, especially at longer time steps. This largely doesn't cause issues until you try to distribute solar radiation at a sub-daily time step onto complex terrain.

**Comment by bartnijssen** [comment]
@klapo : Thanks but not our main concern at the moment. I first want a version of MetSim that reproduces `mtclim` as implemented in VIC and then make improvements to it. At that time the improved solar geometry would be great to include.

**Comment by arbennett** [comment]
Addressed in #17
