### ISSUE TITLE
Add references for longwave & cloud calculations 

### ISSUE THREAD

**Issue by arbennett** [UW-Hydro/MetSim#69]

**Comment by jhamman** [comment]
@arbennett - I think @tbohn will be a good reference for getting this done.

**Comment by bartnijssen** [comment]
@tbohn : Can you let @arbennett which references we need to include in the MetSim documentation for the longwave and cloud calculations?

@arbennett : Can you be specific with @tbohn what you are looking for?

**Comment by arbennett** [comment]
@tbohn What I want to reference are the entries in `cloud_calc` and `emmisivity_calc` within the `metsim/disaggregate.py` module [link](https://github.com/UW-Hydro/MetSim/blob/master/metsim/disaggregate.py#L324-L338).

I think it's hinted at the sources in the VIC code, but I haven't dug into it too much.

**Comment by tbohn** [comment]
Sure, the citations are as follows.  To get the full bibliographic information, look up the citations in Bohn et al. (2013), whose bib info is at the bottom of this comment.  The part of Bohn et al (2013) that talks about these various methods is Appendix A.

emissivity_calc:
DEFAULT - this looks very strange to me - your lambda simply sets emissivity = vp.  Are you sure that's not a typo?  In VIC 4.2, I thought I had set DEFAULT = PRATA since PRATA gave the best performance...  If it's not a typo, i.e. you copied faithfully from VIC 4.2, then I must apologize, it must be a typo in VIC 4.2.  I'd recommend removing this option altogether and making PRATA the default value of emissivity_calc.
TVA - TVA (1972)
ANDERSON - Anderson (1954)
BRUTSAERT - Brutsaert (1975)
SATTERLUND - Satterlund (1979)
IDSO - Idso (1981)
PRATA - Prata (1996)

cloud_calc:
DEFAULT - TVA (1972) - whether this SHOULD be the default is another matter - in Bohn et al (2013) we found that DEARDORFF outperformed TVA.  I'd recommend renaming DEFAULT to "TVA", and then making DEARDORFF the actual default value of cloud_calc.
DEARDORFF - Deardorff (1978)

Bohn, T.J., Livneh, B., Oyler, J.W., Running, S.W., Nijssen, B. and Lettenmaier, D.P., 2013. Global evaluation of MTCLIM and related algorithms for forcing of ecological and hydrological models. Agricultural and forest meteorology, 176, pp.38-49.

**Comment by arbennett** [comment]
@tbohn This is great, thank you!

A couple things:
1. I think I took the initial implementation of these from @jhamman's initial mock up of a standalone MTCLIM.
2. The default emissivity is actually set to `prata`
3. The default cloud is set to `deardorff`

It's probably worth updating these names, as you've said.  At the point this part was being implemented I didn't really understand anything about MTCLIM (or even hydrology for that matter...).

**Comment by tbohn** [comment]
Ah, ok.  I should have looked more closely at the code to see what the actual defaults were.  Thanks for updating the names (and removing the DEFAULT emissivity option altogether as it doesn't really make physical sense).

**Comment by bartnijssen** [comment]
Closed per PR #91
